apiVersion: apps/v1
kind: Deployment
metadata:
  name: myworkflowdemo
  labels:
    app: myworkflowdemo
  namespace: myworkflow-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myworkflowdemo
  template:
    metadata:
      labels:
        app: myworkflowdemo
    spec:
      containers:
        - name: myworkflowdemo
          image: myworkflowacr.azurecr.io/myworkflow-img:latest
          ports:
            - containerPort: 3000