apiVersion: apps/v1
kind: Deployment
metadata:
  name: myworkflowAKS
  labels:
    app: myworkflowAKS
  namespace: myworkflowaks-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myworkflowAKS
  template:
    metadata:
      labels:
        app: myworkflowAKS
    spec:
      containers:
        - name: myworkflowAKS
          image: myworkflowAKSacr.azurecr.io/myworkflowaks-img:latest
          ports:
            - containerPort: 3000