apiVersion: apps/v1
kind: Deployment
metadata:
  name: myazworkflow
  labels:
    app: myazworkflow
  namespace: acraksdem-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myazworkflow
  template:
    metadata:
      labels:
        app: myazworkflow
    spec:
      containers:
        - name: myazworkflow
          image: acraksdem.azurecr.io/acraksdem-img:latest
          ports:
            - containerPort: 3000