apiVersion: v1
kind: Service
metadata:
  name: myazworkflow
  namespace: acraksdem-ns
spec:
  type: LoadBalancer
  selector:
    app: myazworkflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000