apiVersion: v1
kind: Service
metadata:
  name: myaksdemo
  namespace: myaksdemo
spec:
  type: LoadBalancer
  selector:
    app: myaksdemo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000