apiVersion: v1
kind: Service
metadata:
  name: myworkflowAKS
  namespace: myworkflowaks-ns
spec:
  type: LoadBalancer
  selector:
    app: myworkflowAKS
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000