apiVersion: v1
kind: Service
metadata:
  name: myworkflowdemo
  namespace: myworkflow-ns
spec:
  type: LoadBalancer
  selector:
    app: myworkflowdemo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000